// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ievpjbgyrzeucshfnqqf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlldnBqYmd5cnpldWNzaGZucXFmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc5NjIyODAsImV4cCI6MjA3MzUzODI4MH0.zsdUdrb4TZRubM60xl3zxSRCx2QlTi86VTYNj3yQg4A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});